# Generated by Django 5.0.3 on 2024-03-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_rating_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='tmdb_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
