# Generated by Django 5.0.3 on 2024-03-17 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_movie_year'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='movie',
            unique_together={('title', 'year')},
        ),
    ]
